### ISSUE TITLE
display actionable error message when xcodeproj gem is not installed

### ISSUE THREAD

**Issue by craastad** [codemagic-ci-cd/cli-tools#115]
The current error message for running `xcode-project use-profiles` is incomprehensible:
```
% xcode-project use-profiles
Configure code signing settings
Searching for files matching /Users/user/Library/MobileDevice/Provisioning Profiles/*.mobileprovision
Searching for files matching /Users/user/Library/MobileDevice/Provisioning Profiles/*.provisionprofile
List available code signing certificates in keychain /private/var/folders/c9/brbhkbtd14bgt8s36glj8zhw0000gn/T/build__dnzh9z5.keychain
Searching for files matching /Users/user/nevercode/my_macos_app/**/*.xcodeproj
/Users/user/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- xcodeproj (LoadError)
	from /Users/user/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /Users/user/Library/Python/3.8/bin/code_signing_manager.rb:8:in `<main>'
Failed to set code signing settings for macos/Runner.xcodeproj
```

The solution is to run `gem install xcodeproj`.

Can we add a proper error message for this situation so users know they need to run this command? Maybe consider adding a setup validation script? Should we go as far as having a [Bundler Gemfile](https://bundler.io/gemfile.html) (though that would feel strange in a python library)?

**Comment by priitlatt** [comment]
This was resolved by PR #277.
