### ISSUE TITLE
errors when using the python debugger

### ISSUE THREAD

**Issue by DetachHead** [codemagic-ci-cd/cli-tools#222]
this only seems to occur when running with the python debugger in vscode:
![image](https://user-images.githubusercontent.com/57028336/167297426-ff9662ea-c2ca-465f-ab6c-18edf17395bf.png)

the error doesn't occur when clicking  "Run Python File"

### code
```python
from os import environ
from typing import Final

from codemagic.apple.app_store_connect.type_declarations import IssuerId, KeyIdentifier
from codemagic.tools.app_store_connect import AppStoreConnect
from dotenv import load_dotenv

load_dotenv()


app_store_connect: Final = AppStoreConnect(
    KeyIdentifier(environ["APP_STORE_CONNECT_KEY_IDENTIFIER"]),
    IssuerId(environ["APP_STORE_CONNECT_ISSUER_ID"]),
    private_key=environ["APP_STORE_CONNECT_PRIVATE_KEY"],
)

apps = app_store_connect.list_apps()
```
### output
```
Traceback (most recent call last):
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\codemagic\apple\app_store_connect\json_web_token_manager.py", line 148, in get_jwt
    self._jwt = self._load_jwt_from_disk()
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\codemagic\apple\app_store_connect\json_web_token_manager.py", line 102, in _load_jwt_from_disk
    raise JwtCacheError('Disk cache is disabled')
codemagic.apple.app_store_connect.json_web_token_manager.JwtCacheError: Disk cache is disabled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\jwt\algorithms.py", line 416, in prepare_key
    key = load_pem_public_key(key)
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\cryptography\hazmat\primitives\serialization\base.py", line 30, in load_pem_public_key
    return ossl.load_pem_public_key(data)
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 853, in load_pem_public_key
    self._handle_key_loading_error()
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1129, in _handle_key_loading_error
    raise ValueError(
ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [_OpenSSLErrorWithText(code=151584876, lib=9, reason=108, reason_text=b'error:0909006C:PEM routines:get_name:no start line')])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\amogus\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\amogus\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\amogus\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\amogus\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\amogus\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\amogus\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\amogus\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\amogus\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\amogus\IdeaProjects\proj\proj\__init__.py", line 17, in <module>
    apps = app_store_connect.list_apps()
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\codemagic\cli\cli_app.py", line 417, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\codemagic\tools\_app_store_connect\action_groups\apps_action_group.py", line 71, in list_apps
    return self._list_resources(
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\codemagic\tools\_app_store_connect\resource_manager_mixin.py", line 45, in _list_resources
    resources = resource_manager.list(resource_filter=resource_filter)
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\codemagic\apple\app_store_connect\apps\apps.py", line 62, in list
    apps = self.client.paginate(f'{self.client.API_URL}/apps', params=params)
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\codemagic\apple\app_store_connect\api_client.py", line 105, in paginate
    return self._paginate(url, params, page_size, limit).data
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\codemagic\apple\app_store_connect\api_client.py", line 91, in _paginate
    response = self.session.get(url, params={'limit': page_size, **params}).json()
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\codemagic\apple\app_store_connect\api_session.py", line 48, in request
    headers.update(self._auth_headers_factory())
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\codemagic\apple\app_store_connect\api_client.py", line 71, in generate_auth_headers
    return {'Authorization': f'Bearer {self.jwt}'}
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\codemagic\apple\app_store_connect\api_client.py", line 67, in jwt
    jwt = self._jwt_manager.get_jwt()
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\codemagic\apple\app_store_connect\json_web_token_manager.py", line 151, in get_jwt
    self._jwt = self._generate_jwt()
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\codemagic\apple\app_store_connect\json_web_token_manager.py", line 136, in _generate_jwt
    token = self._encode_token(payload)
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\codemagic\apple\app_store_connect\json_web_token_manager.py", line 85, in _encode_token
    return jwt.encode(
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\jwt\api_jwt.py", line 63, in encode
    return api_jws.encode(json_payload, key, algorithm, headers, json_encoder)
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\jwt\api_jws.py", line 113, in encode
    key = alg_obj.prepare_key(key)
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\jwt\algorithms.py", line 418, in prepare_key
    key = load_pem_private_key(key, password=None)
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\cryptography\hazmat\primitives\serialization\base.py", line 22, in load_pem_private_key
    return ossl.load_pem_private_key(data, password)
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 823, in load_pem_private_key
    return self._load_key(
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1070, in _load_key
    self._handle_key_loading_error()
  File "c:\Users\amogus\IdeaProjects\proj\.venv\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1129, in _handle_key_loading_error
    raise ValueError(
ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [_OpenSSLErrorWithText(code=151584876, lib=9, reason=108, reason_text=b'error:0909006C:PEM routines:get_name:no start line')])
```

**Comment by priitlatt** [comment]
@DetachHead, could you please check which `pyOpenSSL` and `cryptography` versions are you using in the virtualenv from which you are debugging it?

**Comment by DetachHead** [comment]
@priitlatt
pyOpenSSL 22.0.0
cryptography 36.0.2

**Comment by priitlatt** [comment]
Thanks. I'll try to reproduce it and see what can be done about it. I'll keep you posted and let you know if I need any more information.

**Comment by priitlatt** [comment]
Hi again @DetachHead. I'm unable to reproduce the described issue using VSCode debugger. Tried it with the following versions:

```
$ python --version                                                     
Python 3.10.2
$ python -m pip freeze | grep -i "\(codemagic\|pyopenssl\|cryptography\)"
codemagic-cli-tools==0.25.0
cryptography==36.0.2
pyOpenSSL==22.0.0
```

Could you please make sure that the debug session is using a valid private key? This can be done by attaching debugger on line `apps = app_store_connect.list_apps()` and inspect the value of `app_store_connect._private_key`. You can check it either from variables section or from interactive debug console.

**Comment by DetachHead** [comment]
my bad, turns out this was actually caused by an issue with `python-dotenv` https://github.com/theskumar/python-dotenv/issues/404
