### ISSUE TITLE
Issues with Xcode 14 update for app-store-connect CLI tool

### ISSUE THREAD

**Issue by asudharsan** [codemagic-ci-cd/cli-tools#264]
I updated to Xcode 14 yesterday and when I try to use the app-store-connect CLI tool, I am getting this error

File "/Users/Automation01/Library/Python/3.8/bin/app-store-connect", line 5, in <module>
    from codemagic.tools import AppStoreConnect
ModuleNotFoundError: No module named 'codemagic'

This is the error I get when I try to do --help command too

**Automation01 % app-store-connect --help
Traceback (most recent call last):
  File "/Users/Automation01/Library/Python/3.8/bin/app-store-connect", line 5, in <module>
    from codemagic.tools import AppStoreConnect
ModuleNotFoundError: No module named 'codemagic' **

Can anyone points if this is due to the update to Xcode 14? Any solution to fix this error?

**Comment by asudharsan** [comment]
After updating the cli tools using `pip3 install --upgrade codemagic-cli-tools` the issue got resolved
